-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users
(
    user_id      int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_name    varchar(255) NULL,
    user_pw      varchar(255) NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);


-- public."role" definition

-- Drop table

-- DROP TABLE public."role";

CREATE TABLE public."role"
(
    role_id   int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name varchar(255) NULL,
    CONSTRAINT pk_role PRIMARY KEY (role_id)
);


-- public.authority definition

-- Drop table

-- DROP TABLE public.authority;

CREATE TABLE public.authority
(
    authority_id   int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    authority_name varchar(255) NULL,
    CONSTRAINT pk_authority PRIMARY KEY (authority_id)
);


-- public.user_role definition

-- Drop table

-- DROP TABLE public.user_role;

CREATE TABLE public.user_role
(
    id_user int8 NOT NULL,
    id_role int8 NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id_user, id_role),
    CONSTRAINT fk_user_role__role FOREIGN KEY (id_role) REFERENCES public."role" (role_id),
    CONSTRAINT fk_user_role__user FOREIGN KEY (id_user) REFERENCES public.users (user_id)
);


-- public.role_authority definition

-- Drop table

-- DROP TABLE public.role_authority;

CREATE TABLE public.role_authority
(
    id_role      int8 NOT NULL,
    id_authority int8 NOT NULL,
    CONSTRAINT pk_role_authority PRIMARY KEY (id_role, id_authority),
    CONSTRAINT fk_role_authority__role FOREIGN KEY (id_role) REFERENCES public."role" (role_id),
    CONSTRAINT fk_role_authority__authority FOREIGN KEY (id_authority) REFERENCES public.authority (authority_id)
);